# my global config
global:
  scrape_interval: 15s
  evaluation_interval: 15s

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets: []

# Load rules once and periodically evaluate them
rule_files: []

# Scrape configuration
scrape_configs:

  # Prometheus sendiri
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
        labels:
          app: "prometheus"

  # Metrics dari model ML
  - job_name: "ml_model"
    static_configs:
      - targets: ["localhost:8000"]
        labels:
          app: "telco-churn-model"