# -*- coding: utf-8 -*-
"""automate_ElsaNurrahmawati.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PCURykDlfPwNERJtdNBMlAQn-pcyUkux
"""

import pandas as pd
import numpy as np

from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler

def preprocess_data(input_file, output_file):

    # Load dataset
    df = pd.read_csv(input_file)

    print("Dataset berhasil dimuat")
    print("Ukuran dataset awal:", df.shape)

    # Menghapus kolom tidak relevan
    df.drop('customerID', axis=1, inplace=True)

    # Menangani missing value pada TotalCharges
    df['TotalCharges'] = df['TotalCharges'].replace(' ', np.nan)

    df['TotalCharges'] = pd.to_numeric(
        df['TotalCharges']
    )

    df['TotalCharges'].fillna(
        df['TotalCharges'].median(),
        inplace=True
    )

    # Menghapus data duplikat
    df.drop_duplicates(inplace=True)

    # Encoding data kategorikal
    le = LabelEncoder()

    for col in df.columns:
        if df[col].dtype == 'object':
            df[col] = le.fit_transform(df[col])

    # Memisahkan fitur dan target
    X = df.drop('Churn', axis=1)
    y = df['Churn']

    # Standardisasi data
    scaler = StandardScaler()

    X_scaled = scaler.fit_transform(X)

    # Membuat Dataset Hasil Preprocessing
    processed_df = pd.DataFrame(
        X_scaled,
        columns=X.columns
    )

    # Penting! reset index agar tidak menghasilkan NaN
    processed_df['Churn'] = y.reset_index(drop=True)

    # Cek missing value
    print("\nMissing Value:")
    print(processed_df.isnull().sum())

    # Menyimpan dataset hasil preprocessing
    processed_df.to_csv(
        output_file,
        index=False
    )

    print("\nPreprocessing berhasil")
    print("Ukuran dataset akhir:", processed_df.shape)
    print(f"Dataset tersimpan sebagai: {output_file}")

if __name__ == "__main__":

    preprocess_data(
        "WA_Fn-UseC_-Telco-Customer-Churn.csv",
        "telco_churn_preprocessed.csv"
    )